stages:
  - app-build
  - docker-build

app-build:
  image: node:latest
  stage: app-build
  artifacts:
    paths:
      - static/frontend/dist/
  script:
    - cd static/frontend
    - npm install -f node-sass
    - npm install
    - npm run build

docker-build:
  image: docker:stable
  stage: docker-build
  variables:
    DOCKER_DRIVER: overlay
  dependencies: 
    - app-build
  script:
  - docker info
  - docker build -t vincentiusrenaldiima/nims-viz .
  - echo "$REGISTRY_USER" | docker login --username "$REGISTRY_USER" --password-stdin
  - docker push vincentiusrenaldiima/nims-viz