stages:
  - app-build
  - docker-build
  - docker-push

app-build:
  image: node:latest
  stage: app-build
  before_script:
    - cd static/frontend
    - npm install -f node-sass
    - npm install
  artifacts:
    paths:
      - static/frontend/dist/
  script:
    - npm run build

docker-build:
  image: docker:stable
  stage: docker-build
  script:
  - docker info
  - docker build -t myimage .