version: "3.5"

services:
  # database:
  #   image: mysql:5.6
  #   hostname: database
  #   environment:
  #     - MYSQL_ROOT_HOST=%
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=platform-finder
  #   ports:
  #     - 3306:3306

  backend:
    # depends_on:
    #   - database
    restart: on-failure
    build:
      context: ./static/backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  frontend:
    depends_on:
      - backend
    restart: on-failure
    build:
      context: ./static/frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
