version: "3.5"

services:
  database:
    container_name: database
    image: mongo:4.2
    ports:
      - 27017:27017

  backend:
    container_name: backend
    depends_on:
      - database
    restart: on-failure
    build:
      context: ./static/backend
      dockerfile: Dockerfile
    environment:
      - env=prod
    ports:
      - 3000:3000
    links:
      - database

  frontend:
    container_name: frontend
    depends_on:
      - backend
    restart: on-failure
    build:
      context: ./static/frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
